spring:
  application:
    name: fintrail-simulator

  datasource:
    url: jdbc:postgresql://localhost:5432/fintrail
    username: devuser
    password: password123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update # Automatically creates tables based on Java classes
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect